### ISSUE TITLE
Data Updater Plant crashes with `value_change` triggers on datastream interfaces

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte#138]
Stacktrace (generated with local Astarte deployment with 0.10-snapshot):
```
astarte-data-updater-plant_1    | 11:48:08.044 [error] GenServer {Registry.DataUpdater, {"test", <<201, 218, 129, 148, 91, 6, 67, 239, 177, 103, 239, 222, 125,
 12, 110, 47>>}} terminating
astarte-data-updater-plant_1    | ** (FunctionClauseError) no function clause matching in Astarte.DataAccess.Data.fetch_property/5
astarte-data-updater-plant_1    |     (astarte_data_access) lib/astarte_data_access/data.ex:37: Astarte.DataAccess.Data.fetch_property({#PID<0.1721.0>, #Refere
nce<0.3067377248.121896968.132174>}, <<201, 218, 129, 148, 91, 6, 67, 239, 177, 103, 239, 222, 125, 12, 110, 47>>, %Astarte.Core.InterfaceDescriptor{aggregatio
n: :individual, automaton: {%{{0, "realValue"} => 1}, %{1 => <<74, 19, 138, 223, 180, 26, 70, 196, 99, 119, 165, 221, 187, 187, 72, 163>>}}, interface_id: <<2,
 224, 206, 164, 78, 230, 132, 21, 68, 58, 174, 138, 98, 46, 5, 104>>, major_version: 0, minor_version: 1, name: "org.astarteplatform.Values", ownership: :devic
e, storage: "individual_datastreams", storage_type: :multi_interface_individual_datastream_dbtable, type: :datastream}, %Astarte.Core.Mapping{allow_unset: fals
e, description: nil, doc: nil, endpoint: "/realValue", endpoint_id: <<74, 19, 138, 223, 180, 26, 70, 196, 99, 119, 165, 221, 187, 187, 72, 163>>, expiry: 0, ex
plicit_timestamp: true, interface_id: <<2, 224, 206, 164, 78, 230, 132, 21, 68, 58, 174, 138, 98, 46, 5, 104>>, path: nil, reliability: :unreliable, retention:
 :discard, type: nil, value_type: :double}, "/realValue")
astarte-data-updater-plant_1    |     (astarte_data_updater_plant) lib/astarte_data_updater_plant/data_updater/impl.ex:346: Astarte.DataUpdaterPlant.DataUpdate
r.Impl.handle_data/6
astarte-data-updater-plant_1    |     (astarte_data_updater_plant) lib/astarte_data_updater_plant/data_updater/server.ex:53: Astarte.DataUpdaterPlant.DataUpdat
er.Server.handle_cast/2
astarte-data-updater-plant_1    |     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
astarte-data-updater-plant_1    |     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
astarte-data-updater-plant_1    |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
astarte-data-updater-plant_1    | Last message: {:"$gen_cast", {:handle_data, "org.astarteplatform.Values", "/realValue", <<12, 0, 0, 0, 16, 118, 0, 8, 0, 0, 0
, 0>>, "test-ydqBlFsGQ--xZ-_e-37E77026732BBA-724F1B33", 15735592586521530}}
astarte-data-updater-plant_1    | State: %Astarte.DataUpdaterPlant.DataUpdater.State{connected: true, data_triggers: %{}, datastream_maximum_storage_retention:
 nil, device_id: <<201, 218, 129, 148, 91, 6, 67, 239, 177, 103, 239, 222, 125, 12, 110, 47>>, device_triggers: %{}, interface_ids_to_name: %{}, interfaces: %{
}, interfaces_by_expiry: [], introspection: %{"org.astarteplatform.Values" => 0}, introspection_triggers: %{}, last_device_triggers_refresh: 0, last_seen_messa
ge: 0, mappings: %{}, message_tracker: #PID<0.1707.0>, paths_cache: {32, %{}}, realm: "test", total_received_bytes: 9089, total_received_msgs: 93, volatile_tri
ggers: []}
astarte-data-updater-plant_1    |
astarte-data-updater-plant_1    | =CRASH REPORT==== 12-Nov-2019::11:48:08 ===
astarte-data-updater-plant_1    |   crasher:
astarte-data-updater-plant_1    |     initial call: Elixir.Astarte.DataUpdaterPlant.DataUpdater.Server:init/1
astarte-data-updater-plant_1    |     pid: <0.1858.0>
astarte-data-updater-plant_1    |     registered_name: []
astarte-data-updater-plant_1    |     exception error: no function clause matching
astarte-data-updater-plant_1    |                      'Elixir.Astarte.DataAccess.Data':fetch_property({<0.1721.0>,
astarte-data-updater-plant_1    |                                                                       #Ref<0.3067377248.121896968.132174>},
astarte-data-updater-plant_1    |                                                                      <<201,218,
astarte-data-updater-plant_1    |                                                                        129,148,
astarte-data-updater-plant_1    |                                                                        91,6,67,
astarte-data-updater-plant_1    |                                                                        239,177,
astarte-data-updater-plant_1    |                                                                        103,239,
astarte-data-updater-plant_1    |                                                                        222,125,
astarte-data-updater-plant_1    |                                                                        12,110,
astarte-data-updater-plant_1    |                                                                        47>>,
astarte-data-updater-plant_1    |                                                                      #{'__struct__' =>
astarte-data-updater-plant_1    |                                                                            'Elixir.Astarte.Core.InterfaceDescriptor',
astarte-data-updater-plant_1    |                                                                        aggregation =>
astarte-data-updater-plant_1    |                                                                            individual,
astarte-data-updater-plant_1    |                                                                        automaton =>
astarte-data-updater-plant_1    |                                                                            {#{{0,
astarte-data-updater-plant_1    |                                                                                <<"realValue">>} =>
astarte-data-updater-plant_1    |                                                                                   1},
astarte-data-updater-plant_1    |                                                                             #{1 =>
astarte-data-updater-plant_1    |                                                                                   <<74,19,
astarte-data-updater-plant_1    |                                                                                     138,223,
astarte-data-updater-plant_1    |                                                                                     180,26,
astarte-data-updater-plant_1    |                                                                                     70,196,
astarte-data-updater-plant_1    |                                                                                     99,119,
astarte-data-updater-plant_1    |                                                                                     165,221,
astarte-data-updater-plant_1    |                                                                                     187,187,
astarte-data-updater-plant_1    |                                                                                     72,163>>}},
astarte-data-updater-plant_1    |                                                                        interface_id =>
astarte-data-updater-plant_1    |                                                                            <<2,224,
astarte-data-updater-plant_1    |                                                                              206,164,
astarte-data-updater-plant_1    |                                                                              78,230,
astarte-data-updater-plant_1    |                                                                              132,21,
astarte-data-updater-plant_1    |                                                                              68,58,
astarte-data-updater-plant_1    |                                                                              174,138,
astarte-data-updater-plant_1    |                                                                              98,46,5,
astarte-data-updater-plant_1    |                                                                              104>>,
astarte-data-updater-plant_1    |                                                                        major_version =>
astarte-data-updater-plant_1    |                                                                            0,
astarte-data-updater-plant_1    |                                                                        minor_version =>
astarte-data-updater-plant_1    |                                                                            1,
astarte-data-updater-plant_1    |                                                                        name =>
astarte-data-updater-plant_1    |                                                                            <<"org.astarteplatform.Values">>,
astarte-data-updater-plant_1    |                                                                        ownership =>
astarte-data-updater-plant_1    |                                                                            device,
astarte-data-updater-plant_1    |                                                                        storage =>
astarte-data-updater-plant_1    |                                                                            <<"individual_datastreams">>,
astarte-data-updater-plant_1    |                                                                        storage_type =>
astarte-data-updater-plant_1    |                                                                            multi_interface_individual_datastream_dbtable,
astarte-data-updater-plant_1    |                                                                        type =>
astarte-data-updater-plant_1    |                                                                            datastream},
astarte-data-updater-plant_1    |                                                                      #{'__struct__' =>
astarte-data-updater-plant_1    |                                                                            'Elixir.Astarte.Core.Mapping',
astarte-data-updater-plant_1    |                                                                        allow_unset =>
astarte-data-updater-plant_1    |                                                                            false,
astarte-data-updater-plant_1    |                                                                        description =>
astarte-data-updater-plant_1    |                                                                            nil,
astarte-data-updater-plant_1    |                                                                        doc =>
astarte-data-updater-plant_1    |                                                                            nil,
astarte-data-updater-plant_1    |                                                                        endpoint =>
astarte-data-updater-plant_1    |                                                                            <<"/realValue">>,
astarte-data-updater-plant_1    |                                                                        endpoint_id =>
astarte-data-updater-plant_1    |                                                                            <<74,19,
astarte-data-updater-plant_1    |                                                                              138,223,
astarte-data-updater-plant_1    |                                                                              180,26,
astarte-data-updater-plant_1    |                                                                              70,196,
astarte-data-updater-plant_1    |                                                                              99,119,
astarte-data-updater-plant_1    |                                                                              165,221,
astarte-data-updater-plant_1    |                                                                              187,187,
astarte-data-updater-plant_1    |                                                                              72,163>>,
astarte-data-updater-plant_1    |                                                                        expiry =>
astarte-data-updater-plant_1    |                                                                            0,
astarte-data-updater-plant_1    |                                                                        explicit_timestamp =>
astarte-data-updater-plant_1    |                                                                            true,
astarte-data-updater-plant_1    |                                                                        interface_id =>
astarte-data-updater-plant_1    |                                                                            <<2,224,
astarte-data-updater-plant_1    |                                                                              206,164,
astarte-data-updater-plant_1    |                                                                              78,230,
astarte-data-updater-plant_1    |                                                                              132,21,
astarte-data-updater-plant_1    |                                                                              68,58,
astarte-data-updater-plant_1    |                                                                              174,138,
astarte-data-updater-plant_1    |                                                                              98,46,5,
astarte-data-updater-plant_1    |                                                                              104>>,
astarte-data-updater-plant_1    |                                                                        path =>
astarte-data-updater-plant_1    |                                                                            nil,
astarte-data-updater-plant_1    |                                                                        reliability =>
astarte-data-updater-plant_1    |                                                                            unreliable,
astarte-data-updater-plant_1    |                                                                        retention =>
astarte-data-updater-plant_1    |                                                                            discard,
astarte-data-updater-plant_1    |                                                                        type =>
astarte-data-updater-plant_1    |                                                                            nil,
astarte-data-updater-plant_1    |                                                                        value_type =>
astarte-data-updater-plant_1    |                                                                            double},
astarte-data-updater-plant_1    |                                                                      <<"/realValue">>) (lib/astarte_data_access/data.ex, line
 37)
astarte-data-updater-plant_1    |       in function  'Elixir.Astarte.DataUpdaterPlant.DataUpdater.Impl':handle_data/6 (lib/astarte_data_updater_plant/data_upda
ter/impl.ex, line 346)
astarte-data-updater-plant_1    |       in call from 'Elixir.Astarte.DataUpdaterPlant.DataUpdater.Server':handle_cast/2 (lib/astarte_data_updater_plant/data_up
dater/server.ex, line 53)
astarte-data-updater-plant_1    |       in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
astarte-data-updater-plant_1    |       in call from gen_server:handle_msg/6 (gen_server.erl, line 686)
astarte-data-updater-plant_1    |     ancestors: ['Elixir.Astarte.DataUpdaterPlant.AMQPDataConsumer',
astarte-data-updater-plant_1    |                   'Elixir.Astarte.DataUpdaterPlant.Supervisor',<0.1527.0>]
astarte-data-updater-plant_1    |     message_queue_len: 0
astarte-data-updater-plant_1    |     messages: []
astarte-data-updater-plant_1    |     links: [<0.1532.0>]
astarte-data-updater-plant_1    |     dictionary: []
astarte-data-updater-plant_1    |     trap_exit: false
astarte-data-updater-plant_1    |     status: running
astarte-data-updater-plant_1    |     heap_size: 2586
astarte-data-updater-plant_1    |     stack_size: 27
astarte-data-updater-plant_1    |     reductions: 6758
astarte-data-updater-plant_1    |   neighbours:
```

**Comment by rbino** [comment]
Closed by #517
