### ISSUE TITLE
AppEngine crash on encoded group names

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astarte#456]
creating a group with name `!"£$%&/()=?^` crashes AppEngine when quering for the group devices

```
GET https://api.my.astarte.cloud/appengine/v1/test/groups/!%22%C2%A3%24%25%26%2F()%3D%3F%5E/devices?details=true
```

Image log
```
Aug  6 15:57:31 |ERRO| #PID<0.12226.4> running Astarte.AppEngine.APIWeb.Endpoint (connection #PID<0.12214.4>, stream id 2) terminated
Server: api.eu1.astarte.cloud:80 (http)
Request: GET /v1/pavij/groups/!%22%C2%A3%24%25%26%2F()%3D%3F%5E/devices?details=true
** (exit) an exception was raised:
    ** (ArgumentError) malformed URI "!\"£$%&/()=?^"
        (elixir 1.10.3) lib/uri.ex:344: URI.decode/1
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api_web/controllers/device_status_by_group_controller.ex:36: Astarte.AppEngine.APIWeb.DeviceStatusByGroupController.index/2
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api_web/controllers/device_status_by_group_controller.ex:18: Astarte.AppEngine.APIWeb.DeviceStatusByGroupController.action/2
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api_web/controllers/device_status_by_group_controller.ex:18: Astarte.AppEngine.APIWeb.DeviceStatusByGroupController.phoenix_controller_pipeline/2
        (phoenix 1.5.4) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api_web/endpoint.ex:18: Astarte.AppEngine.APIWeb.Endpoint.plug_builder_call/2
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api_web/endpoint.ex:18: Astarte.AppEngine.APIWeb.Endpoint.call/2
        (phoenix 1.5.4) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
```

**Comment by Pavinati** [comment]
This is not an issue, the group name must be encoded twice, once to escape symbols, and once again to escape control characters that may alter the URL path semantic
```
GET /v1/pavij/groups/!%2522%25C2%25A3%2524%2525%2526%252F()%253D%253F%255E/devices?details=true
```
yelds the expected data
