### ISSUE TITLE
AppEngine crashes when GETting values for a parameterized aggregated interface

### ISSUE THREAD

**Issue by davidebriani** [astarte-platform/astarte#480]
I registered the following interface:

```json
{
  "interface_name": "datastream.aggregated",
  "version_major": 1,
  "version_minor": 0,
  "type": "datastream",
  "ownership": "device",
  "aggregation": "object",
  "mappings": [
    {
      "endpoint": "/objects/%{param}/value/array",
      "type": "doublearray",
      "explicit_timestamp": true
    },
    {
      "endpoint": "/objects/%{param}/value/x",
      "type": "double",
      "explicit_timestamp": true
    },
    {
      "endpoint": "/objects/%{param}/value/y",
      "type": "double",
      "explicit_timestamp": true
    },
    {
      "endpoint": "/objects/%{param}/value/z",
      "type": "double",
      "explicit_timestamp": true
    }
  ]
}

```

Then used the Elixir SDK to pair a device and send some datastream values:

```elixir
Astarte.Device.send_datastream(pid, "datastream.aggregated", "/objects/position/value", %{ x: 10, y: 70, z: 0, array: [1, 2, 3] })
Astarte.Device.send_datastream(pid, "datastream.aggregated", "/objects/position/value", %{ x: 11, y: 71, z: 1, array: [2, 3, 4] })
```

All good. Elixir SDK, DUP and Realm management showed no errors so far.
Then I queried for the interface's values on the Dashboard and AppEngine correctly returned the list of values.

If I send some more values for another endpoint's parameter (velocity):

```elixir
Astarte.Device.send_datastream(pid, "datastream.aggregated", "/objects/velocity/value", %{ x: 10, y: 70, z: 0, array: [1, 2, 3] })
Astarte.Device.send_datastream(pid, "datastream.aggregated", "/objects/velocity/value", %{ x: 11, y: 71, z: 1, array: [2, 3, 4] })
```

All good. Elixir SDK, DUP and Realm management showed no errors so far.
But then I queried for the interface's values on the Dashboard and AppEngine responded with a 500 error. Logs follow:

```
Oct 14 09:41:46 |ERRO| #PID<0.733.195> running Astarte.AppEngine.APIWeb.Endpoint (connection #PID<0.476.195>, stream id 12) terminated
Server: api.eu1.astarte.cloud:80 (http)
Request: GET /v1/davidebriani/devices/CUPVU9qTQOeRPjfkHMvPYA/interfaces/datastream.aggregated
** (exit) an exception was raised:
    ** (CQEx.Error) "Order by currently only support the ordering of columns following their declared order in the PRIMARY KEY (Code 8704)\nStatement: SELECT  v_z,  v_y,  v_x,  v_array,  reception_timestamp FROM datastream_aggregated_v1 WHERE device_id=:device_id  AND path=:path  ORDER BY reception_timestamp DESC LIMIT :limit_nrows ;;\nValues: %{device_id: <<9, 67, 213, 83, 218, 147, 64, 231, 145, 62, 55, 228, 28, 203, 207, 96>>, limit_nrows: 1, path: \"/objects/velocity/value\"}"
        (cqex 1.0.1) lib/cqex/query.ex:116: CQEx.Query.call!/2
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api/device/queries.ex:1210: Astarte.AppEngine.API.Device.Queries.retrieve_object_datastream_values/6
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api/device/device.ex:1245: Astarte.AppEngine.API.Device.retrieve_endpoint_values/9
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api/device/device.ex:1184: anonymous fn/7 in Astarte.AppEngine.API.Device.retrieve_endpoint_values/9
        (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api/device/device.ex:1182: Astarte.AppEngine.API.Device.retrieve_endpoint_values/9
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api/device/device.ex:992: Astarte.AppEngine.API.Device.do_get_interface_values!/9
        (astarte_appengine_api 1.0.0-alpha.1) lib/astarte_appengine_api_web/controllers/interface_values_controller.ex:57: Astarte.AppEngine.APIWeb.InterfaceValuesController.show/2
```

**Comment by davidebriani** [comment]
I run some tests also with the interface listed in https://github.com/astarte-platform/astarte-dashboard/issues/176
and it still crashes when submitting values for two (or more) different parameters
