### ISSUE TITLE
Scylla reverse read memory problem

### ISSUE THREAD

**Issue by isaak42** [astarte-platform/astarte#728]
Hi, I'm running an Astarte cluster on Kubernetes and have run into the following problem twice now with a particular sensor my company is running that produces a much higher volume of data than any other sensor we are running.

Here are the logs from the appengine pod (with some information redacted):

```
level=info ts=2022-07-25T10:33:00.354+00:00 msg="Sent reply." status_code=500 elapsed=316ms realm=<realm> device_id=<device_id> interface=<our_reverse_domain>.PSIValues path=a42ce283-46b5-4545-8603-e2cd340326c8/1/psiLevel module=PlugLoggerWithMeta function=call/2 request_id=5fb5d79f746cf366240b544b213bc925 tag=sent_reply

level=error ts=2022-07-25T10:33:00.355+00:00 msg="#PID<0.13392.224> running Astarte.AppEngine.APIWeb.Endpoint (connection #PID<0.5244.224>, stream id 133) terminated
Server: api.astarte.<our_domain>.com:80 (http)
Request: GET /v1/<realm>/devices/<device_id>/interfaces/<our_reverse_domain>.PSIValues/a42ce283-46b5-4545-8603-e2cd340326c8/1/psiLevel?limit=1
 (exit) an exception was raised:
    ** (CQEx.Error) \"Operation failed for <realm>.individual_datastreams - received 0 responses and 1 failures from 1 CL=ONE. (Code 4864)\
Statement: SELECT value_timestamp, reception_timestamp, reception_timestamp_submillis, double_value  FROM individual_datastreams  WHERE device_id=:device_id AND interface_id=:interface_id AND endpoint_id=:endpoint_id AND path=:path   ORDER BY value_timestamp DESC, reception_timestamp DESC, reception_timestamp_submillis DESC LIMIT :limit_nrows\
Values: %{device_id: <<19, 116, 115, 233, 143, 186, 81, 47, 129, 96, 169, 190, 213, 13, 229, 236>>, endpoint_id: <<249, 238, 145, 197, 112, 48, 166, 155, 23, 67, 15, 231, 100, 81, 182, 145>>, interface_id: <<238, 136, 112, 108, 168, 4, 86, 16, 125, 123, 89, 196, 105, 135, 100, 190>>, limit_nrows: 1, path: \\"/a42ce283-46b5-4545-8603-e2cd340326c8/1/psiLevel\\"}\"
        (cqex 1.0.1) lib/cqex/query.ex:116: CQEx.Query.call!/2
        (astarte_appengine_api 1.0.1) lib/astarte_appengine_api/device/queries.ex:1290: Astarte.AppEngine.API.Device.Queries.retrieve_datastream_values/7
        (astarte_appengine_api 1.0.1) lib/astarte_appengine_api/device/device.ex:1284: Astarte.AppEngine.API.Device.retrieve_endpoint_values/9
        (astarte_appengine_api 1.0.1) lib/astarte_appengine_api_web/controllers/interface_values_controller.ex:46: Astarte.AppEngine.APIWeb.InterfaceValuesController.show/2
        (astarte_appengine_api 1.0.1) lib/astarte_appengine_api_web/controllers/interface_values_controller.ex:18: Astarte.AppEngine.APIWeb.InterfaceValuesController.action/2
        (astarte_appengine_api 1.0.1) lib/astarte_appengine_api_web/controllers/interface_values_controller.ex:18: Astarte.AppEngine.APIWeb.InterfaceValuesController.phoenix_controller_pipeline/2
        (phoenix 1.5.8) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (astarte_appengine_api 1.0.1) lib/astarte_appengine_api_web/endpoint.ex:18: Astarte.AppEngine.APIWeb.Endpoint.plug_builder_call/2"
```

I'm using a separate Scylla database cluster to store Astarte data, and I found out that the Scylla query Astarte is making is failing. Here are the logs from the Scylla pod:
```
ERROR 2022-07-25 10:32:51,490 [shard 0] storage_proxy - Exception when communicating with 10.12.3.179, to read from <realm>.individual_datastreams: std::runtime_error (Memory usage of reversed read exceeds hard limit of 104857600 (configured via max_memory_for_unlimited_query_hard_limit), while reading partition 137473e9-8fba-512f-8160-a9bed50de5ec:ee88706c-a804-5610-7d7b-59c4698764be:f9ee91c5-7030-a69b-1743-0fe76451b691:/a42ce283-46b5-4545-8603-e2cd340326c8/1/psiLevel)
```

It looks like the entire dataset is being read and reversed to get the most recent items. Is there a way to better query this data so I don't run into this problem? Other than increasing the amount of memory allowed in this particular Scylla setting?

**Comment by Pavinati** [comment]
That happens when data has to be reordered by Scylla, like when you ask for the latest data sent on a specific endpoint or querying an interface using only the `to` parameter.
A common solution to those problems is to limit the number of samples Scylla has to reorder.
For example, when searching for the latest data sent by a device, include the `since` parameter with a meaningful date, for example 1 week ago, so you don't have to load the whole device history.

**Comment by samubd** [comment]
I think that current issue is a blocking issue when querying the appengine APIs in a specific interface level (i.e. /devices/DEVICEID/interfaces/INTERFACEID ) since the API returns the last value for each endoint and there is no way to limit the number of samples here.
